package com.gemini.watermark.remover

import android.annotation.SuppressLint
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.os.Bundle
import android.provider.OpenableColumns
import android.view.View
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.lifecycle.lifecycleScope
import androidx.recyclerview.widget.LinearLayoutManager
import com.gemini.watermark.remover.adapter.ImageListAdapter
import com.gemini.watermark.remover.core.WatermarkEngine
import com.gemini.watermark.remover.databinding.ActivityMainBinding
import com.gemini.watermark.remover.model.ProcessingItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.InputStream

class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding

    /** Temporary bitmap for saving */
    private var pendingBitmap: Bitmap? = null

    /** Launcher for saving images using CREATE_DOCUMENT */
    private val saveImageLauncher = registerForActivityResult(
        ActivityResultContracts.CreateDocument("image/jpeg")
    ) { uri ->
        uri?.let {
            pendingBitmap?.let { bitmap ->
                saveBitmapToUri(bitmap, it)
                pendingBitmap = null
            }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }

        setSupportActionBar(binding.toolbar)
        supportActionBar?.setDisplayShowTitleEnabled(false)

        setupUploadArea()
        setupResetButton()
    }

    private fun setupUploadArea() {
        binding.uploadCard.setOnClickListener {
            val intent = Intent(Intent.ACTION_GET_CONTENT).apply {
                type = "image/*"
                putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true)
            }
            startActivityForResult(intent, REQUEST_CODE_PICK_IMAGES)
        }
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == REQUEST_CODE_PICK_IMAGES && resultCode == RESULT_OK) {
            val clipData = data?.clipData
            if (clipData != null && clipData.itemCount > 1) {
                val uris = mutableListOf<Uri>()
                for (i in 0 until clipData.itemCount) {
                    uris.add(clipData.getItemAt(i).uri)
                }
                showMultiPreview(uris)
            } else {
                val singleUri = data?.data ?: clipData?.getItemAt(0)?.uri
                singleUri?.let { showSinglePreview(it) }
            }
        }
    }

    /** Single image preview & processing */
    private fun showSinglePreview(uri: Uri) {
        binding.singlePreview.root.visibility = View.VISIBLE
        binding.multiPreview.root.visibility = View.GONE

        val original = loadBitmap(uri) ?: run {
            showToast("Failed to load image")
            return
        }

        lifecycleScope.launch(Dispatchers.IO) {
            try {
                val engine = WatermarkEngine.create(applicationContext)
                val result = engine.removeWatermark(original)
                withContext(Dispatchers.Main) {
                    binding.singlePreview.comparisonSlider.setImages(original, result)
                    binding.singlePreview.originalInfo.visibility = View.VISIBLE
                    binding.singlePreview.processedInfo.visibility = View.VISIBLE
                    binding.singlePreview.downloadBtn.visibility = View.VISIBLE

                    // Download button
                    binding.singlePreview.downloadBtn.setOnClickListener {
                        downloadSingleBitmap(result, uri)
                    }
                }
                engine.release()
            } catch (_: Exception) {
                withContext(Dispatchers.Main) {
                    showToast("This image is not generated by Gemini AI")
                    binding.singlePreview.root.visibility = View.GONE
                }
            }
        }
    }

    /** Multi-image preview & processing */
    @SuppressLint("SetTextI18n")
    private fun showMultiPreview(uris: List<Uri>) {
        binding.singlePreview.root.visibility = View.GONE
        binding.multiPreview.root.visibility = View.VISIBLE

        val items = uris.map { ProcessingItem(it) }
        val adapter = ImageListAdapter(items) { item ->
            item.processedBitmap?.let { bitmap ->
                downloadSingleBitmap(bitmap, item.uri)
            }
        }

        binding.multiPreview.imageList.layoutManager = LinearLayoutManager(this)
        binding.multiPreview.imageList.adapter = adapter
        binding.multiPreview.progressText.text = "Processing: 0/${items.size}"

        lifecycleScope.launch(Dispatchers.IO) {
            val engine = WatermarkEngine.create(applicationContext)
            var processedCount = 0

            for ((index, item) in items.withIndex()) {
                try {
                    val original = loadBitmap(item.uri)
                    if (original != null) {
                        val result = engine.removeWatermark(original)
                        item.processedBitmap = result
                    } else {
                        item.error = true
                    }
                } catch (_: Exception) {
                    item.error = true
                }

                processedCount++
                withContext(Dispatchers.Main) {
                    adapter.notifyItemChanged(index)
                    binding.multiPreview.progressText.text =
                        "Processing: $processedCount/${items.size}"
                }
            }

            engine.release()

            withContext(Dispatchers.Main) {
                binding.multiPreview.downloadAllBtn.visibility = View.VISIBLE
                binding.multiPreview.downloadAllBtn.setOnClickListener {
                    downloadMultipleBitmaps(items)
                }
            }
        }
    }

    /** Reset previews */
    private fun setupResetButton() {
        binding.singlePreview.resetBtn.setOnClickListener {
            binding.singlePreview.root.visibility = View.GONE
            binding.multiPreview.root.visibility = View.GONE
        }
    }

    /** Load bitmap safely from URI */
    private fun loadBitmap(uri: Uri): Bitmap? {
        return try {
            val inputStream: InputStream? = contentResolver.openInputStream(uri)
            BitmapFactory.decodeStream(inputStream).also { inputStream?.close() }
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    /** Get filename from URI */
    private fun getFileName(uri: Uri): String {
        val cursor = contentResolver.query(uri, null, null, null, null)
        cursor?.use {
            val nameIndex = it.getColumnIndex(OpenableColumns.DISPLAY_NAME)
            if (it.moveToFirst()) return it.getString(nameIndex)
        }
        return "image.png"
    }

    /** Generate "_unwatermarked" filename */
    private fun getUnwatermarkedFileName(uri: Uri): String {
        val originalName = getFileName(uri)
        val dotIndex = originalName.lastIndexOf('.')
        return if (dotIndex != -1) {
            val name = originalName.substring(0, dotIndex)
            val extension = originalName.substring(dotIndex)
            "${name}_unwatermarked${extension}"
        } else {
            "${originalName}_unwatermarked.png"
        }
    }

    /** Download a single bitmap */
    private fun downloadSingleBitmap(bitmap: Bitmap, uri: Uri) {
        val filename = getUnwatermarkedFileName(uri)
        pendingBitmap = bitmap
        saveImageLauncher.launch(filename)
    }

    /** Download multiple bitmaps (multi-preview) */
    private fun downloadMultipleBitmaps(items: List<ProcessingItem>) {
        items.forEach { item ->
            item.processedBitmap?.let { bitmap ->
                val filename = getUnwatermarkedFileName(item.uri)
                pendingBitmap = bitmap
                saveImageLauncher.launch(filename)
            }
        }
    }

    /** Save bitmap to URI */
    private fun saveBitmapToUri(bitmap: Bitmap, uri: Uri) {
        try {
            contentResolver.openOutputStream(uri)?.use { out ->
                bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
                out.flush()
                showToast("Image saved: ${uri.lastPathSegment}")
            }
        } catch (e: Exception) {
            showToast("Failed to save image")
            e.printStackTrace()
        }
    }

    /** Show toast message */
    private fun showToast(message: String) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
    }

    companion object {
        private const val REQUEST_CODE_PICK_IMAGES = 100
    }
}